// <auto-generated />
using Antivirus.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Antivirus.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Antivirus.Models.Benefit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Benefits");
                });

            modelBuilder.Entity("Antivirus.Models.Bootcamp", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Bootcamps");
                });

            modelBuilder.Entity("Antivirus.Models.InstituteBootcamp", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("BootcampId")
                        .HasColumnType("bigint");

                    b.Property<long?>("InstitutionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BootcampId");

                    b.HasIndex("InstitutionId");

                    b.ToTable("InstituteBootcamps");
                });

            modelBuilder.Entity("Antivirus.Models.InstituteOpportunity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("InstitutionId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OpportunityId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("InstitutionId");

                    b.HasIndex("OpportunityId");

                    b.ToTable("InstituteOpportunities");
                });

            modelBuilder.Entity("Antivirus.Models.Institution", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BienestarLink")
                        .HasColumnType("text");

                    b.Property<string>("CarerLink")
                        .HasColumnType("text");

                    b.Property<string>("GeneralLink")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Observations")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ProccesLink")
                        .HasColumnType("text");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.Property<long?>("UbicationInstitutionId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UbicationsInstitutionsId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UbicationInstitutionId");

                    b.ToTable("Institutions");
                });

            modelBuilder.Entity("Antivirus.Models.Opportunity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AdicionalDates")
                        .HasColumnType("text");

                    b.Property<string>("Applications")
                        .HasColumnType("text");

                    b.Property<long?>("CategoriesId")
                        .HasColumnType("bigint");

                    b.Property<string>("ContactChannels")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Guide")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Observations")
                        .HasColumnType("text");

                    b.Property<long?>("OpportunityTypeId")
                        .HasColumnType("bigint");

                    b.Property<string>("Requirements")
                        .HasColumnType("text");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.Property<long?>("StatusReviewId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Opportunities");
                });

            modelBuilder.Entity("Antivirus.Models.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Usuario",
                            Status = true
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Admin",
                            Status = true
                        });
                });

            modelBuilder.Entity("Antivirus.Models.Service", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("Antivirus.Models.UbicationInstitution", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("UbicationInstitutions");
                });

            modelBuilder.Entity("Antivirus.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("DateBirth")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("LastName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Antivirus.Models.UserBootcamp", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("BootcampId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BootcampId");

                    b.HasIndex("UserId");

                    b.ToTable("UserBootcamps");
                });

            modelBuilder.Entity("Antivirus.Models.UserOpportunity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("OpportunityId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OpportunityId");

                    b.HasIndex("UserId");

                    b.ToTable("UserOpportunities");
                });

            modelBuilder.Entity("Antivirus.Models.UserRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Antivirus.Models.InstituteBootcamp", b =>
                {
                    b.HasOne("Antivirus.Models.Bootcamp", null)
                        .WithMany("InstituteBootcamps")
                        .HasForeignKey("BootcampId");

                    b.HasOne("Antivirus.Models.Institution", null)
                        .WithMany("InstituteBootcamps")
                        .HasForeignKey("InstitutionId");
                });

            modelBuilder.Entity("Antivirus.Models.InstituteOpportunity", b =>
                {
                    b.HasOne("Antivirus.Models.Institution", null)
                        .WithMany("InstituteOpportunities")
                        .HasForeignKey("InstitutionId");

                    b.HasOne("Antivirus.Models.Opportunity", null)
                        .WithMany("InstituteOpportunities")
                        .HasForeignKey("OpportunityId");
                });

            modelBuilder.Entity("Antivirus.Models.Institution", b =>
                {
                    b.HasOne("Antivirus.Models.UbicationInstitution", null)
                        .WithMany("Institutions")
                        .HasForeignKey("UbicationInstitutionId");
                });

            modelBuilder.Entity("Antivirus.Models.UserBootcamp", b =>
                {
                    b.HasOne("Antivirus.Models.Bootcamp", null)
                        .WithMany("UsersBootcamps")
                        .HasForeignKey("BootcampId");

                    b.HasOne("Antivirus.Models.User", null)
                        .WithMany("UsersBootcamps")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Antivirus.Models.UserOpportunity", b =>
                {
                    b.HasOne("Antivirus.Models.Opportunity", null)
                        .WithMany("UserOpportunities")
                        .HasForeignKey("OpportunityId");

                    b.HasOne("Antivirus.Models.User", null)
                        .WithMany("UserOpportunities")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Antivirus.Models.UserRole", b =>
                {
                    b.HasOne("Antivirus.Models.Role", null)
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Antivirus.Models.User", null)
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Antivirus.Models.Bootcamp", b =>
                {
                    b.Navigation("InstituteBootcamps");

                    b.Navigation("UsersBootcamps");
                });

            modelBuilder.Entity("Antivirus.Models.Institution", b =>
                {
                    b.Navigation("InstituteBootcamps");

                    b.Navigation("InstituteOpportunities");
                });

            modelBuilder.Entity("Antivirus.Models.Opportunity", b =>
                {
                    b.Navigation("InstituteOpportunities");

                    b.Navigation("UserOpportunities");
                });

            modelBuilder.Entity("Antivirus.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Antivirus.Models.UbicationInstitution", b =>
                {
                    b.Navigation("Institutions");
                });

            modelBuilder.Entity("Antivirus.Models.User", b =>
                {
                    b.Navigation("UserOpportunities");

                    b.Navigation("UserRoles");

                    b.Navigation("UsersBootcamps");
                });
#pragma warning restore 612, 618
        }
    }
}
